version: "3.9"
services:
  zmm:
    image: windymelt/zmm:latest
    volumes:
      - "./:/app"
    working_dir: /app
    environment:
      - "VOICEVOX_URI=http://voicevox-cpu:50021"
      - "CHROMIUM_CMD=chromium-browser"
      - "CHROMIUM_NOSANDBOX=1"
  # どっちかを動かしてください
  voicevox-cpu:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - "50021:50021"
    mem_limit: 4g
  voicevox-gpu:
    image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
    ports:
      - "50021:50021"
    mem_limit: 4g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
