name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-distribution: [ 'temurin' ]
        java-version: [ '17' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}
          cache: 'sbt'
      - name: Install sbt
        run: curl -Ls https://raw.githubusercontent.com/dwijnand/sbt-extras/master/sbt > ./sbt && chmod 0755 ./sbt
      - uses: coursier/cache-action@v6
      - name: Test
        run: ./sbt test
