name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'sbt'
      - name: Install sbt
        run: curl -Ls https://raw.githubusercontent.com/dwijnand/sbt-extras/master/sbt > /bin/sbt && chmod 0755 /bin/sbt
      - uses: coursier/cache-action@v6
      - name: sbt scalafmtAll
        run: /bin/sbt scalafmtAll
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply scalafmt
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-distribution: [ 'temurin' ]
        java-version: [ '17' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}
          cache: 'sbt'
      - name: Install sbt
        run: curl -Ls https://raw.githubusercontent.com/dwijnand/sbt-extras/master/sbt > /bin/sbt && chmod 0755 /bin/sbt
      - uses: coursier/cache-action@v6
      - name: Test
        run: /bin/sbt test
