name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checkFmt:
    name: Scalafmt/Scalafix check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'sbt'
      - uses: coursier/cache-action@v6
      - name: sbt scalafmtCheckAll; scalafixAll --check
        run: sbt 'scalafmtCheckAll; scalafixAll --check'
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-distribution: [ 'temurin' ]
        java-version: [ '17' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java-distribution }}
          java-version: ${{ matrix.java-version }}
          cache: 'sbt'
      - uses: coursier/cache-action@v6
      - name: Test
        run: sbt scalafmtSbtCheck scalafmtCheckAll test
